// Sports action types.
export const FETCH_SPORTS_BEGIN = "FETCH_SPORTS_BEGIN";
export const FETCH_SPORTS_SUCCESS = "FETCH_SPORTS_SUCCESS";
export const FETCH_SPORTS_FAILURE = "FETCH_SPORTS_FAILURE";
export const UPDATE_SPORT = "UPDATE_SPORT";
export const CREATE_SPORT = "CREATE_SPORT";

// Countries action types.
export const FETCH_COUNTRIES_BEGIN = "FETCH_COUNTRIES_BEGIN";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const CREATE_COUNTRY = "CREATE_COUNTRY";

// Leagues action types.
export const FETCH_LEAGUES_BEGIN = "FETCH_LEAGUES_BEGIN";
export const FETCH_LEAGUES_SUCCESS = "FETCH_LEAGUES_SUCCESS";
export const FETCH_LEAGUES_FAILURE = "FETCH_LEAGUES_FAILURE";
export const UPDATE_LEAGUE = "UPDATE_LEAGUE";
export const CREATE_LEAGUE = "CREATE_LEAGUE";
